### ISSUE TITLE
Provide à la carte pi-spi device tree overlays

### ISSUE THREAD

**Issue by jangevaare** [widgetlords/libwidgetlords#1]
It would be helpful to me if device trees were offered separately for the pi-spi series such that 5 pins did not need to be blocked to use the library - especially with GPIO4 so commonly used with Raspberry Pi for 1wire support! Cheers.

**Comment by widgetlords** [comment]
As far as we know it isn't possible to do this nicely with the way device tree overlays currently work. With the v2.0 library it is now possible redefine certain slave select pins via overlay parameters:
`dtoverlay=pi-spi:ss2_pin=8`
This effectively blocks the overlay from claiming GPIO4 for the SPI bus.

**Comment by jangevaare** [comment]
OK, thanks.
