### ISSUE TITLE
SPI Errors in Node-Red on Raspberry Pi4

### ISSUE THREAD

**Issue by MaddyTP** [widgetlords/libwidgetlords#3]
Continuous error in Node-red log:

![image](https://user-images.githubusercontent.com/45469378/84204576-52259b00-aa60-11ea-850c-d17adedee789.png)

Running Raspi over SPI-DIN series:
(1) 2x4MIO
(1) 4AO
(1) 4KO
(2) 8AI

**Comment by Enjoy-Combi** [comment]
Hi,

Did you do this: npm install node-red-contrib-widgetlords ?

**Comment by MaddyTP** [comment]
Installed on Node-Red through pallet manager node-red-contrib-widgetlords (version 1.3.0) and installed the libraries per instruction on the website:

```
wget https://github.com/widgetlords/libwidgetlords/releases/download/v2.1.0/libwidgetlords_2.1.0_armhf.deb
sudo dpkg -i libewidgetlords_2.1.0_armhf.deb
```

It seem the SPI setup on the Pi4 is different than the Pi3.  My setup is as follows:

PI-SPI-DIN-2x4MIO
PI-SPI-DIN-8AI (20ma)
PI-SPI-DIN-8AI (5v)
PI-SPI-DIN-4KO

All works except the 2x4MIO.  Relays work on this board, but analog out, digital pins, and SDAFE do not work.  This makes sense when considering the errors mentioned above as libwidgetlords/overlays/vpe-2901a.dts appears to be setting SPI5-7 for I/Os that don't work:

```
                       spidev@5{
				compatible = "spidev";
				reg = <5>;	/* CE_2AO */
				#address-cells = <1>;
				#size-cells = <0>;
				spi-max-frequency = <1000000>;
			};

			spidev@6{
				compatible = "spidev";
				reg = <6>;	/* CE_SDAFE1 */
				#address-cells = <1>;
				#size-cells = <0>;
				spi-max-frequency = <1000000>;
			};

			spidev@7{
				compatible = "spidev";
				reg = <7>;	/* CE_SDAFE2 */
				#address-cells = <1>;
				#size-cells = <0>;
				spi-max-frequency = <1000000>;
			};
```

**Comment by MaddyTP** [comment]
Seeing same issue on Raspberry Pi 3B+ with identical setup.

![image](https://user-images.githubusercontent.com/45469378/85173264-a92d2c00-b227-11ea-8ae5-abf320d0ea18.png)

**Comment by MaddyTP** [comment]
Both RP4 and RP4 only exposes five:

![image](https://user-images.githubusercontent.com/45469378/85174505-5b65f300-b22a-11ea-80bb-936e0c67c507.png)

**Comment by MaddyTP** [comment]
Turns out I was following the instructions too closely.  

dtoverlay=vpe-2701c is not applicable if you are using vpe-2901a...
